#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" != "Darwin*" ]; then
    echo "Error, only for MacOS!"
    exit 2
fi

brew update
brew install make
brew install zsh
brew upgrade
brew doctor
brew cleanup
