# Taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"

# apps
brew "brew-cask-completion"
brew "hugo"
brew "p7zip"
brew "zip"
brew "fd"
brew "fdupes"
brew "ffmpeg"

# TODO: aspell

# Cask
cask_args appdir: "/Applications"

cask "cakebrew"
cask "firefox"
cask "google-chrome"
cask "gimp"
cask "unetbootin"
cask "skype"
cask "adobe-acrobat-reader"
