# https://github.com/d12frosted/homebrew-emacs-plus
# brew info emacs-plus

tap "d12frosted/emacs-plus"

brew "emacs-plus", args: [
        "with-ctags", 
        "with-dbus", 
        "with-modern-icon", 
        "with-jansson",
        "without-spacemacs-icon",
        # "with-x11",
        # "with-xwidgets",
        "HEAD"
    ]

brew "cask"
